apiVersion: apps/v1
kind: Deployment
metadata:
  name: selforderapp
  labels:
    app: selforderapp
spec:
  selector:
    matchLabels:
      app: selforderapp
  replicas: 3
  template:
    metadata:
      labels:
        app: selforderapp
    spec:
      containers:
        - name: selforderapp
          image: hocinemab/springkubernetes:1.0
          ports:
            - containerPort: 8080
          env:   # Setting Environmental Variables
            - name: DB_HOST   #    Setting Database host address
              value: mysql
            - name: DB_NAME  # Setting Database name
              value: selforder
            - name: DB_USERNAME  # Setting Database username
              value: root
            - name: DB_PASSWORD # Setting Database password
              value: root
          resources:
             requests:
               cpu: 100m
               memory: 256Mi
             limits:
               cpu: 500m
               memory: 512Mi   
# This seperator --- below is MANDATORY!!!
---
# Define a 'Service' To Expose the application
apiVersion: v1
kind: Service
metadata:
  name: seflorderappservice
spec:
  ports:
    - protocol: "TCP"
      port: 8080    # Port inside the cluster
      targetPort: 8080   # Port exposed to the outside
  selector:
    app: selforderapp
  type: NodePort