name: DockerImgeBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        maven: [ '3.5.4', '3.6.3', '3.8.2' ]
        java: [ '8', '11', '16', '17']

    steps:
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.2.1
      with:
        java-version: ${{ matrix.java }}
        maven-version: ${{ matrix.maven }}
    - name: Build with Maven
      run: mvnw 
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag selforderapp:$(date +%s)
    - name: Build the Docker image
      run: docker login -u hocinemab -p ${{secrets.DOCKERPW}} && docker push hocinemab/selforderapp:$(date +%s)
