name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag selforder:$(date +%s)
    - name: push the Docker image
      run: docker login -u hcoinemab -p ${{ secrets.dokerpw }} && docker push selforder:$(date +%s)
