name: DockerImgeBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest    

    steps:
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19' 
    - name: action-maven 
      uses: comchangs/action-maven@v0.4-beta    
    - name: build with maven
      run: mvnw clean instal -DskipeTests
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag selforderapp:$(date +%s)
    - name: Build the Docker image
      run: docker login -u hocinemab -p ${{secrets.DOCKERPW}} && docker push hocinemab/selforderapp:$(date +%s)
