name: DockerImgeBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest    

    steps:
    - name: Composite java action
  # You may pin to the exact commit or the version.
  # uses: evryfs/composite-java-action@2d4393c69c59d706ffc23c625abb557b991e6acb
    - uses: evryfs/composite-java-action@v0.3.11     
      
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag selforderapp:$(date +%s)
    - name: Build the Docker image
      run: docker login -u hocinemab -p ${{secrets.DOCKERPW}} && docker push hocinemab/selforderapp:$(date +%s)
