name: DockerImgeBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest    

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
    - name: npm/yarn/pnpm install
  # uses: Jaid/action-npm-install@9483da054882538350947c4147de4c8adbf0d597
      uses: Jaid/action-npm-install@v1.2.4  
   
    - uses: actions/checkout@v2
    - name: Angular Full CI
  
  # uses: colbyhill21/angular-full-ci@a3489087f6a715db335078f999c01d422a254a6c
      uses: colbyhill21/angular-full-ci@v1.0

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
     
    - name: Build with Maven
      run: mvn clean install -DskipTests=true
    - name: Build the Docker image    
      run: docker build . --file dockerfile --tag selforderapp:$(date +%s)
    - name: Build the Docker image
      run: docker login -u hocinemab -p ${{secrets.DOCKERPW}} && docker push hocinemab/selforderapp:$(date +%s)
